apiVersion: apps/v1
kind: Deployment
metadata:
  name: stopover-frontend
  labels:
    app: stopover-frontend
    environment: dev 
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stopover-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: stopover-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: stopover-frontend
        image: devopsppecontainerregistry.azurecr.io/frontend/stopover-frontend:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: JWT_TOKEN
          valueFrom:
            secretKeyRef:
              name: stopover-frontend-secret
              key: JWT_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: stopover-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: stopover-frontend
